"use client"
import { ReactNode } from 'react'
import { Provider } from 'react-redux'
import './globals.css'
import { store } from './store'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({children,}: {children: ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
